### ISSUE TITLE
Parameter store backend

### ISSUE THREAD

**Issue by jgjorgji-h4** [telia-oss/concourse-sts-lambda#21]
I see that you've removed the parameter store backend, would you be interested in adding both parameter store and secrets functionality in this tool?

Also on master the README is wrong since without S3 config it fails and it's not mentioned anywhere.

**Comment by itsdalmo** [comment]
Hi @jgjorgji-h4 and thanks for the issue. I've been wanting to add back parameter store for this resource, but perhaps not as part of this repository, but instead a rewrite for a more "generic" secrets provider that I started (but have not had the time to finish) here:
https://github.com/telia-oss/concourse-credentials-lambda

**Comment by jhosteny** [comment]
Hi @itsdalmo - is the generic provider WIP you reference available somewhere? We are looking at implementing IAM and Github token rotation, but would like to use SSM instead of Secrets Manager. I'd be interested in taking a look at what you've done so far if possible. Thanks!

**Comment by itsdalmo** [comment]
Hi @jhosteny! You can find the code here now: https://github.com/telia-oss/sidecred

You can see it's still got some WIP stuff there that I did not have a chance to finish before vacation. I'll pick it up again when I'm back in a couple of weeks👍

**Comment by jhosteny** [comment]
@itsdalmo thanks, that looks great!

**Comment by itsdalmo** [comment]
Please take a look at `sidecred` @jgjorgji-h4 - I will be focusing on that project going forward and not making any new releases for `concourse-sts-lambda`.
