### ISSUE TITLE
Can we have a release?

### ISSUE THREAD

**Issue by mohsen0** [telia-oss/concourse-sts-lambda#25]
I am after this fix,
https://github.com/telia-oss/concourse-sts-lambda/pull/23

**Comment by itsdalmo** [comment]
Done in the following release: https://github.com/telia-oss/concourse-sts-lambda/releases/tag/v1.1.0

**Comment by itsdalmo** [comment]
PS: I had to move the `v1.1.0` tag after merging #28

**Comment by itsdalmo** [comment]
Seems the credentials for doing releases had expired, `v1.1.0` was moved again and now includes bumped dependencies and its now building with Go 1.14. Just FYI.
